# controller/app.py
import docker
import uuid
import os
import logging
from flask import Flask, request, redirect, url_for, render_template_string

logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')

app = Flask(__name__)

REVERSE_PROXY_BASE_URL = os.getenv('REVERSE_PROXY_BASE_URL', 'http://localhost')
logging.info(f"Using REVERSE_PROXY_BASE_URL: {REVERSE_PROXY_BASE_URL}")
if REVERSE_PROXY_BASE_URL == 'http://localhost':
    logging.warning("REVERSE_PROXY_BASE_URL is set to default 'http://localhost'. "
                    "This is likely incorrect for Codespaces. Ensure it's set via environment variable.")

FIREFOX_IMAGE = "jlesage/firefox:latest"
FIREFOX_INTERNAL_PORT = "5800"
DOCKER_NETWORK = "proxy_network"
STOP_PASSWORD = "1234"  # Password to stop sessions

client = None
try:
    client = docker.from_env()
    client.ping()
    logging.info("Successfully connected to Docker daemon.")
except Exception as e:
    logging.error(f"Fatal Error: Could not connect to Docker daemon: {e}")

active_sessions = {}
status_log_messages = []

def add_status(message):
    logging.info(message)
    status_log_messages.insert(0, f"[{os.times().elapsed:.2f}s] {message}")
    while len(status_log_messages) > 10:
        status_log_messages.pop()

HOME_PAGE_HTML = """
<!DOCTYPE html>
<html>
<head>
