version: "3.8"

services:
  reverse-proxy:
    image: traefik:v2.11
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - proxy_network

  controller:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      REVERSE_PROXY_BASE_URL: ${REVERSE_PROXY_BASE_URL:-http://localhost}
    ports:
      - "5000:5000"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - proxy_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.controller_route.rule=PathPrefix(`/`)"
      - "traefik.http.routers.controller_route.entrypoints=web"
      - "traefik.http.services.controller_service.loadbalancer.server.port=5000"

networks:
  proxy_network:
    external: true
